version: '3.8'

services:
  mcp-server:
    container_name: mcp-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./src:/app/src
    restart: unless-stopped